# Generated by Django 6.0.5 on 2026-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharelink",
            name="password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
