# Generated by Django 6.0.5 on 2026-05-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_sharelink_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uploader_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
