# Generated by Django 5.0 on 2026-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_document_uploader_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                ("use_tls", models.BooleanField(default=True)),
                (
                    "from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email settings",
                "verbose_name_plural": "Email settings",
            },
        ),
    ]
